[theme]
base = "dark"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#e8e8e8"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
